### ISSUE TITLE
Unable to overwrite existing dictionaries

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-publish#36]
```Publishing [======================----------------------------] failed to set service config up for Helix 0.0serror: Remote publish service failed StatusCodeError: 500 - {"message":"FastlyError: Duplicate dictionary: 'strain_refs'","stack":["FastlyError: Duplicate dictionary: 'strain_refs'","    at request.then (/nodejsAction/XXinHgIj/node_modules/@adobe/fastly-native-promises/src/httpclient.js:79:17)","    at process._tickCallback (internal/process/next_tick.js:68:7)"],"status":"error"}
error: Error while running the Publish command: Error: Unable to setup service config
    at request.post.then.catch (/usr/local/node_modules/hlx/node_modules/@adobe/helix-cli/src/remotepublish.cmd.js:165:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)Unable to setup service config
Error while running the Publish command
```

Using following config: https://github.com/trieloff/helix-demo/blob/81c2a71791d322eea6df5aa9fd0162f81c2f9a79/helix-config.yaml on Service ID `3l2MjGcHgWw5NUJz7OKYH3`, version 1039

**Comment by trieloff** [comment]
Underlying issue: https://github.com/adobe/fastly-native-promises/issues/50
