### ISSUE TITLE
hlx publish fails on newly created demo project

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-publish#52]
**Description**
After creating a new project with `hlx demo test-project` and successfully running `hlx deploy`, `hlx publish` fails with the following error:

```
Publishing [======================----------------------------] failed to set service config up for Helix 0.0serror: Remote publish service failed StatusCodeError: 500 - {"message":"FastlyError: Couldn't find Dictionary '{ deleted => 0000-00-00 00:00:00, name => strain_github_static_root, service => 7lJ8jndU0aEBdKxIn0VRmS, version => 8 }'","stack":["FastlyError: Couldn't find Dictionary '{ deleted => 0000-00-00 00:00:00, name => strain_github_static_root, service => 7lJ8jndU0aEBdKxIn0VRmS, version => 8 }'","    at request.then (/nodejsAction/XXGDeNpK/node_modules/@adobe/fastly-native-promises/src/httpclient.js:82:17)","    at process._tickCallback (internal/process/next_tick.js:68:7)"],"status":"error"}
error: Error while running the Publish command: Error: Unable to setup service config
    at request.post.then.catch (/Users/stefan/projects/helix-cli/src/remotepublish.cmd.js:171:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)Unable to setup service config
Error while running the Publish command
```

The related POST to the `helix-publish` action:

```
{
    "configuration": {
        "version": 1,
        "strains": {
            "local-dev": {
                "code": {
                    "protocol": "http",
                    "host": "localhost",
                    "port": "",
                    "hostname": "localhost",
                    "owner": "local",
                    "repo": "default",
                    "ref": "",
                    "path": ""
                },
                "content": {
                    "protocol": "http",
                    "host": "localhost",
                    "port": "",
                    "hostname": "localhost",
                    "owner": "local",
                    "repo": "default",
                    "ref": "",
                    "path": ""
                },
                "static": {
                    "magic": false,
                    "allow": [],
                    "deny": [],
                    "protocol": "http",
                    "host": "localhost",
                    "port": "",
                    "hostname": "localhost",
                    "owner": "local",
                    "repo": "default",
                    "ref": "",
                    "path": "/htdocs"
                },
                "directoryIndex": "index.html",
                "package": "",
                "sticky": false,
                "condition": "",
                "perf": {
                    "device": "",
                    "location": "",
                    "connection": ""
                },
                "urls": ["http://localhost:3000/"],
                "url": "http://localhost:3000/"
            },
            "default": {
                "code": {
                    "protocol": "https",
                    "host": "github.com",
                    "port": "",
                    "hostname": "github.com",
                    "owner": "stefan-guggisberg",
                    "repo": "hello-helix",
                    "ref": "master",
                    "path": ""
                },
                "content": {
                    "protocol": "https",
                    "host": "github.com",
                    "port": "",
                    "hostname": "github.com",
                    "owner": "stefan-guggisberg",
                    "repo": "hello-helix",
                    "ref": "master",
                    "path": ""
                },
                "static": {
                    "magic": false,
                    "allow": [],
                    "deny": [],
                    "protocol": "https",
                    "host": "github.com",
                    "port": "",
                    "hostname": "github.com",
                    "owner": "stefan-guggisberg",
                    "repo": "hello-helix",
                    "ref": "master",
                    "path": "/htdocs"
                },
                "directoryIndex": "index.html",
                "package": "sguggisb/600b43d92a3d206687c051d2bd1b35e839bb9c2a",
                "sticky": false,
                "condition": "",
                "perf": {
                    "device": "",
                    "location": "",
                    "connection": ""
                },
                "urls": []
            }
        }
    },
    "service": "xxxxxxxxxxxxxxxxxxxxxxxx",
    "token": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "version": 19
}
```
 
**To Reproduce**
1. `hlx demo test-project && cd test-project`
2. `hlx deploy`
3. `git add . && git commit -m 'updated config'`
4. `hlx publish`
5. see Error

**Expected behavior**
Publishing a newly created demo project should succeed (assuming correct fastly and openwhisk env setup).

**Screenshots**

**Version:**
`hlx 0.13.13-pre.2`

**Additional context**
The error could be reliably reproduced. Running once `hlx deploy --no-remote` though was successful and the error went away, i.e. it could not be reproduced anymore.

**Comment by trieloff** [comment]
It looks like we have a race condition when creating dictionaries for the first time:

- create dictionary (body received): 09:58:13.831
- get dictionary (request started): 09:58:12.269

Odd.

**Comment by trieloff** [comment]
AH. Not a race condition, but a caching issue. The GET request during the initialization gets memoized (even with the 404 response), leading to another (wrong) 404 when running the update.

**Comment by trieloff** [comment]
Fix is on the way…
