### ISSUE TITLE
Cannot Update Config

### ISSUE THREAD

**Issue by stevengill** [adobe/helix-publish#6]
```
hlx publish --remote
Publishing [======================----------------------------] failed to set service config up for Helix 0.0serror: Remote publish service failed StatusCodeError: 500 - {"message":"Error: Duplicate dictionary_item: 'dictionary_id=2Fp4MGR34grljezWGSjFAH item_key=default service_id=0gDEZCgYFsF773b88iAgvS'","stack":["Error: Duplicate dictionary_item: 'dictionary_id=2Fp4MGR34grljezWGSjFAH item_key=default service_id=0gDEZCgYFsF773b88iAgvS'","    at request.then (/nodejsAction/XXBmpMgG/node_modules/@adobe/fastly-native-promises/src/httpclient.js:32:17)","    at propagateAslWrapper (/node_modules/async-listener/index.js:502:23)","    at /node_modules/async-listener/glue.js:188:31","    at /node_modules/async-listener/index.js:539:70","    at /node_modules/async-listener/glue.js:188:31","    at process._tickCallback (internal/process/next_tick.js:68:7)"],"status":"error"}
error: Error while running the Publish command: Error: Unable to setup service config
    at request.post.then.catch (/Users/steveng/repo/helix/helix-cli/src/remotepublish.cmd.js:165:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error while running the Publish command
```

**Comment by trieloff** [comment]
@stevengill can you give me access to the service config and share the `helix-config.yaml` you have been using? As I wrote in https://github.com/adobe/fastly-native-promises/issues/31#issuecomment-462298328 I'm not yet able to reproduce this in an integration test.

**Comment by tripodsan** [comment]
maybe the error was caused due to rate-limits ?

**Comment by filmaj** [comment]
@trieloff the config.yaml is over in our public repo: https://github.com/adobe/developer.adobe.com/blob/master/helix-config.yaml - whatever is in here is what is deployed out to https://adobedevsite.helix-demo.xyz/

I don't think I have management/admin access to the fastly service but its namespace or service ID is `0gDEZCgYFsF773b88iAgvS`.

**Comment by trieloff** [comment]
Thank you!

**Comment by trieloff** [comment]
Digging into this bug a bit more, I've noticed that I could not reproduce it reliably, so I spun up a tracing proxy and read the HTTP chatter.

The underlying issue is that the Fastly API sometimes does not respond, i.e in this request/response pair:

```http
GET /service/6E6ge7REhiWetPCqy9jht2/version/121/dictionary/strain_github_static_root HTTP/1.1
Fastly-Key: …
host: api.fastly.com
accept: application/json
content-length: 0
Connection: close

Network error: curl (6) Couldn't resolve host name
```

When that happens, the normal `PUT` requests that set the dict value get replaced with `POST` requests that will subsequently fail.

In normal operations, you will see a sequence of `PUT` request/response pairs like this:

```http
PUT /service/6E6ge7REhiWetPCqy9jht2/dictionary/0NFRzmIVNppN024oaDqH1a/item/helix-demo HTTP/1.1
Fastly-Key: …
host: api.fastly.com
content-type: application/x-www-form-urlencoded
accept: application/json
content-length: 20
Connection: close

item_value=%2Fhtdocs

HTTP/1.1 200 OK
Status: 200 OK
Content-Type: application/json
Cache-Control: no-cache
Fastly-RateLimit-Remaining: 708
Fastly-RateLimit-Reset: 1551351600
Accept-Ranges: bytes
Via: 1.1 varnish
Content-Length: 127
Accept-Ranges: bytes
Date: Thu, 28 Feb 2019 10:24:30 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-control-slwdc9036-CONTROL-SLWDC, cache-hhn1551-HHN
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Timer: S1551349470.243346,VS0,VE259
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000

{"dictionary_id":"0NFRzmIVNppN024oaDqH1a","service_id":"6E6ge7REhiWetPCqy9jht2","item_key":"helix-demo","item_value":"/htdocs"}
```

but following a fail to read the dictionary (see above), we get requests/responses like this:

```http
POST /service/6E6ge7REhiWetPCqy9jht2/dictionary/0NFRzmIVNppN024oaDqH1a/item HTTP/1.1
Fastly-Key: …
host: api.fastly.com
content-type: application/x-www-form-urlencoded
accept: application/json
content-length: 48
Connection: close

item_key=xd-marketing-local&item_value=%2Fhtdocs


HTTP/1.1 409 Conflict
Status: 409 Conflict
Content-Type: application/json
Cache-Control: no-cache
Fastly-RateLimit-Remaining: 692
Fastly-RateLimit-Reset: 1551351600
Accept-Ranges: bytes
Via: 1.1 varnish
Content-Length: 165
Accept-Ranges: bytes
Date: Thu, 28 Feb 2019 10:24:30 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-control-slwdc9036-CONTROL-SLWDC, cache-hhn1526-HHN
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Timer: S1551349470.432555,VS0,VE274
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000

{"msg":"Duplicate record","detail":"Duplicate dictionary_item: 'dictionary_id=0NFRzmIVNppN024oaDqH1a item_key=xd-marketing-local service_id=6E6ge7REhiWetPCqy9jht2'"}
```

Looking at the code in `fastly-native-promises`

https://github.com/adobe/fastly-native-promises/blob/0548f12214958b4de7476340db79b17c766957f1/src/index.js#L803-L828

```javascript
  writeDictItem(version, name, key, value) {
    return this.readDictItem(version, name, key)
      .then(() => {
        // the dictionary item already exists
        if (value) {
          // update existing value
          return this.updateDictItem(version, name, key, value);
        }
        // value is undefined. Fastly does not support overwriting with empty
        // values, so we delete the value
        return this.deleteDictItem(version, name, key);
      })
      .catch(() => {
        // the dictionary item does not exist
        if (value) {
          return this.createDictItem(version, name, key, value);
        }
        // the item does not exist and there is no data to write, we just pretend it went ok
        return {
          status: 200,
          data: {
            status: 'ok',
          },
        };
      });
  }
```

it's clear that we get thrown into the `catch` block upon failure to `readDictItem`, which is then trying the erroneous attempt to `POST` instead of `PUT`.

**Comment by trieloff** [comment]
There are a few things we could do to make this process more robust, all in `fastly-native-promises`

- memoize (cache) the responses to `GET` requests. For each dictionary, we are making 20 identical `GET` requests
- enable retries for `GET` requests that fail due to flaky network or timeouts
- implement [`PATCH /items`](https://docs.fastly.com/api/config#dictionary_item_40bd364dad67e55f6f7edb92a82a4fd0) to bulk update multiple items, further reducing number of requests
