### ISSUE TITLE
Cannot publish the really first time

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-publish#628]
Create a new Fastly service, define only the domain (i.e. `*.hlx-4.page`)

Run `hlx publish`: 

```
Using regular Publish
{ progress: true, level: '****', message: 'preparing fastly transaction' }
{ progress: true, level: '****', message: 'preparing service config for Helix' }
{ progress: true, level: '****', message: 'failed to set service config up for Helix' }
error: Remote publish service failed Error: 500 - "{
  "message": "FastlyError: Couldn't find VCL '{ deleted => 0000-00-00 00:00:00, name => queries.vcl, service => **********************, version => 2 }'",
  "stack": ["FastlyError: Couldn't find VCL '{ deleted => 0000-00-00 00:00:00, name => queries.vcl, service => **********************, version => 2 }'", "    at response.text.then (/nodejsAction/tUZhLdKY/main.js:1191:57)", "    at process._tickCallback (internal/process/next_tick.js:68:7)"],
  "status": "error"
}"
error: Error while running the Publish command: Error: Unable to setup service config
    at fetch.then.catch (/home/circleci/project/node_modules/@adobe/helix-cli/src/remotepublish.cmd.js:378:13)
    at process._tickCallback (internal/process/next_tick.js:68:7) Error: Unable to setup service config
    at fetch.then.catch (/home/circleci/project/node_modules/@adobe/helix-cli/src/remotepublish.cmd.js:378:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error while running the Publish command
```

**Comment by kptdobe** [comment]
The error is not always the same:

```
hlx publish
Publishing [==------------------------------------------------] preparing fastly transaction 0.0s{ progress: true, level: 'info', message: 'preparing fastly transaction' }
Publishing [====----------------------------------------------] preparing service config for Helix 8.1s{ progress: true, level: 'info', message: 'preparing service config for Helix' }
Publishing [=======================---------------------------] failed to set service config up for Helix 25.2s{ progress: true, level: 'info', message: 'failed to set service config up for Helix' }
error: Remote publish service failed Error: 500 - "{
  "message": "Error: Response aborted",
  "stack": ["Error: Response aborted", "    at Object../node_modules/fetch-h2/dist/lib/body.js (/nodejsAction/R8zCxtxb/main.js:35092:20)", "    at __webpack_require__ (/nodejsAction/R8zCxtxb/main.js:30:30)", "    at Object../node_modules/fetch-h2/dist/index.js (/nodejsAction/R8zCxtxb/main.js:34996:16)", "    at __webpack_require__ (/nodejsAction/R8zCxtxb/main.js:30:30)", "    at Object../node_modules/@adobe/helix-fetch/src/index.js (/nodejsAction/R8zCxtxb/main.js:4510:5)", "    at __webpack_require__ (/nodejsAction/R8zCxtxb/main.js:30:30)", "    at Object../node_modules/@adobe/helix-status/src/index.js (/nodejsAction/R8zCxtxb/main.js:13136:18)", "    at __webpack_require__ (/nodejsAction/R8zCxtxb/main.js:30:30)", "    at Object../src/index.js (/nodejsAction/R8zCxtxb/main.js:70843:26)", "    at __webpack_require__ (/nodejsAction/R8zCxtxb/main.js:30:30)"],
  "status": "error"

```

**Comment by kptdobe** [comment]
Note that running another `hlx publish` (no changes) fix the issue.

**Comment by kptdobe** [comment]
Note that running another `hlx publish` (no changes) fix the issue.

**Comment by trieloff** [comment]
I'm pretty sure it's the race condition in the Fastly API.
